[UN-1594] No error message when tokenAddress is not a valid token
unicrowio/sdk pull request #132
Opened 2023-03-10 21:42 UTC by weeebr

https://popstand.atlassian.net/browse/UN-1594

Scenario 1:
![image](https://user-images.githubusercontent.com/1096639/224433685-5decb6b4-566d-40e7-adb7-1fb22d19d0f6.png)

Scenario 2:
![image](https://user-images.githubusercontent.com/1096639/224433799-689b7cca-c249-456a-a357-4ad3c1169be6.png)

2023-03-10 23:43 UTC, ps1dr3x approved these changes

2023-03-11 00:09 UTC, ps1dr3x approved these changes

2023-03-13 16:23 UTC, tgmarinho requested changes

2023-03-13 16:23 UTC, tgmarinho commented on src/core/getTokenInfo.ts
> +    await token.name();
use symbol instead of name here

2023-03-13 16:23 UTC, tgmarinho commented on src/core/getTokenInfo.ts
> +  toast.error(`Can't get info from tokenAddress: ${tokenAddress}`);
you can't use `toast` inside of the core function, only in the UI functions/modal

2023-03-13 16:23 UTC, tgmarinho commented on src/ui/internal/modals/Pay.tsx
> +    "",
What is this empty string `""` and `true` as a parameter?

2023-03-13 18:36 UTC, ps1dr3x approved these changes

2023-03-13 20:12 UTC, tgmarinho approved these changes

2023-03-13 20:13 UTC, merged